---
- name: Generate /etc/hosts for all of the nodes
  blockinfile:
    dest: /etc/hosts
    block: |
        {% for host in groups['all'] %}
        {% set hostnames = hostvars[host]['inventory_hostname'] %}
        {{ hostvars[host]['ansible_host'] }} {{ hostnames }}
        {% endfor %}
