---
- hosts: all
  gather_facts: no
  become: true
  
  tasks:
    - name: configure netplan
      template:
        src: 01-netcfg.yaml.j2
        dest: /etc/netplan/01-netcfg.yaml
        backup: yes
      notify: netplan apply

  handlers:
    - name: netplan apply
      command: netplan apply
